
spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:board0320
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        #show_sql: true
        format_sql: true

  security:
    user:
      name: user
      password: 1234


server:
  port: 7989
  servlet:
    encoding:
      force-response: true


logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

